version: '2'

services:
  asclepius:
    depends_on:
      - chiron
    image: tomtoothfairies/asclepius:1.0

  panacea:
    depends_on:
      - asclepius
    image: tomtoothfairies/panacea:1.0
    ports:
      - '4000:4000'

  chiron:
    image: tomtoothfairies/chiron:1.0
