version: '2'

services:
  asclepius:
    image: tomtoothfairies/asclepius:0.3

  panacea:
    image: tomtoothfairies/panacea:0.3
    ports:
      - '4000:4000'

  chiron:
    image: tomtoothfairies/chiron:latest
