version: '2'

services:
  asclepius:
    image: tomtoothfairies/asclepius:0.2

  panacea:
    image: tomtoothfairies/panacea:0.2
    ports:
      - '4000:4000'

  chiron:
    image: tomtoothfairies/chiron:latest
