version: '2'

services:
  asclepius:
    image: tomtoothfairies/asclepius:latest
    depends_on:
      - chiron

  panacea:
    depends_on:
      - asclepius
    image: tomtoothfairies/panacea:latest

  chiron:
    image: tomtoothfairies/chiron:latest

  selenium:
    image: selenium/standalone-firefox:latest

  athloi:
    depends_on:
      - selenium
      - panacea
    image: tomtoothfairies/athloi:latest
