version: '2'

services:
  asclepius:
    image: tomtoothfairies/asclepius:latest

  panacea:
    image: tomtoothfairies/panacea:latest
    ports:
      - '4000:4000'

  chiron:
    image: tomtoothfairies/chiron:latest
