version: '2'

services:
  asclepius:
    image: tomtoothfairies/asclepius:2.0
    depends_on:
      - chiron

  panacea:
    depends_on:
      - asclepius
    image: tomtoothfairies/panacea:2.0

  chiron:
    image: tomtoothfairies/chiron:2.0

  selenium:
    image: selenium/standalone-firefox:latest

  athloi:
    depends_on:
      - selenium
      - panacea
    image: tomtoothfairies/athloi:2.0
