* Tom and the Toothfairies
** Installation
This project includes a Dockerfile (targeting Ubuntu 16.0.4) for easy
installation and testing. Installation instructions for Docker can be found
[[https://docs.docker.com/engine/installation/linux/ubuntu/][here]].

For docker installations on Ubuntu sudo is required to run docker commands
unless you add your user to the docker group as outlined [[http://askubuntu.com/a/477554][here]]. When running
Ubuntu in a VM, misconfigured DNS may cause issues connecting to outside hosts
in containers. This can be solved by editing
~/etc/NetworkManager/NetworkManager~ and commenting out the line ~dns=dnsmasq~
and then running ~sudo restart network-manager~

1) Clone the Repo
   #+BEGIN_SRC bash
   $ git clone https://github.com/tom-and-the-toothfairies/pathways.git
   #+END_SRC
2) Build with Docker
   #+BEGIN_SRC bash
   $ cd pathways
   $ docker build -t pathways .
   #+END_SRC
   NOTE - [[https://github.com/jnoll/peos][peos]] builds on Ubuntu 16.0.4 but emits warnings which can be ignored.
3) Run the tests
   #+BEGIN_SRC bash
   $ docker run pathways
   #+END_SRC
   This will run pmlcheck on a [[https://github.com/jnoll/peos/blob/master/compiler/models/martini.pml][sample pml file]], then load a subset of DINTO and report the number of triples.
