* Tom and the Toothfairies
[[https://github.com/syl20bnr/spacemacs][https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]] [[https://circleci.com/gh/tom-and-the-toothfairies/pathways][https://img.shields.io/circleci/project/github/tom-and-the-toothfairies/pathways.svg]]
** Installation
This project includes a Docker Compose file for easy installation and testing.
Installation instructions for Docker on your platform can be found [[https://www.docker.com/products/docker][here]].

For Docker installations on Ubuntu ~sudo~ is required to run Docker commands.
*** The Happy Path
If you do not wish to build the Docker containers yourself you can run it
directly from the Docker registry. First, install the necessary Docker
components for your operating system as outlined above.

Then you can run the latest release from [[https://hub.docker.com/r/tomtoothfairies/pathways/][Docker Hub]]
#+BEGIN_SRC bash
$ docker-compose up -d
#+END_SRC
You will then be able to access the web interface at ~http://localhost:4000~
You can stop the Docker containers with:
#+BEGIN_SRC bash
$ docker-compose down
#+END_SRC

To run a release other than the current you may manually checkout the release
tag and run ~docker-compose~
#+BEGIN_SRC bash
$ git checkout 0.2
$ docker-compose up -d
#+END_SRC

*** Building Manually
There are DNS problems when running containers in *Ubuntu* within the *TCD
network*. This can be resolved while on the TCD network by editing the Docker
DNS config.
#+BEGIN_SRC bash
$ echo "{\"dns\": [\"134.226.251.200\", \"134.226.251.100\"]}" | sudo tee -a /etc/docker/daemon.json
$ sudo service docker restart
#+END_SRC
You should revert these settings when leaving the TCD network by running
#+BEGIN_SRC bash
$ sudo rm /etc/docker/daemon.json
$ sudo service docker restart
#+END_SRC

1) Clone the Repo
   #+BEGIN_SRC bash
   $ git clone https://github.com/tom-and-the-toothfairies/pathways.git
   #+END_SRC
2) Build with Docker
   #+BEGIN_SRC bash
   $ cd pathways/asclepius
   $ docker build -t tomtoothfairies/asclepius .
   $ cd ../panacea
   $ docker build -t tomtoothfairies/panacea .
   #+END_SRC
3) Run the tests
   #+BEGIN_SRC bash
   $ docker run -e "MIX_ENV=test" tomtoothfairies/panacea mix test
   #+END_SRC

** Development
Docker can be used for development as follows:
#+BEGIN_SRC bash
$ cd pathways
$ docker run -v $PWD:/code -it --rm tomtoothfairies/pathways bash
#+END_SRC
This will run ~bash~ in a container with the current working directory available
at ~/code~ in the container
