* Asclepius ⚕
Flask endpoint for querying DINTO. Supports querying for all drugs listed, as well as finding all, or specific drug-drug interactions.

** Setup
*** DINTO Ontology Selection
By default, the application uses ~DINTO/DINTO 1/DINTO_1.owl~ as its ontology.
This can be overriden by setting the ~ASCLEPIUS_ONTOLOGY_FILE~ environment variable.

*Note*: As the ontology is rather large, startup can take upwards of 3 minutes.

** Endpoints
*** ~/ping~
| Description | Check endpoint availability |
| Methods     | ~GET~                       |
| Parameters  | None                        |
| Returns     | HTTP 204 (No Content)       |
*** ~/all_drugs~
| Description | Find all drugs in the DINTO ontology                                                  |
| Methods     | ~GET~                                                                                 |
| Parameters  | None                                                                                  |
| Returns     | A list containing pairs of the canonical URI for a drug, as well as its English Label |

**** Example
***** Response Body
#+BEGIN_SRC json
[
  {
    "label" : "tranylcypromine",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_DB0001"
  },
  {
    "label" : "methysergide",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_DB0002"
  },
  {
    "label" : "drospirenone",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_DB9999"
  }
]
#+END_SRC

*** ~/all_ddis~
| Description | Find all drug-drug interactions (DDIs) in the DINTO ontology                                           |
| Methods     | ~GET~                                                                                                  |
| Parameters  | None                                                                                                   |
| Returns     | A list containing pairs of the canonical URI for a drug-drug interaction, as well as its English Label |

**** Example
***** Response Body
#+BEGIN_SRC json
[
  {
    "label" : "tranylcypromine/vilazodone DDI",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_08338"
  },
  {
    "label" : "penbutolol/methysergide DDI",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_07540"
  },
  {
    "label" : "drospirenone/heparin DDI",
    "uri" : "http://purl.obolibrary.org/obo/DINTO_03086"
  }
]
#+END_SRC

*** ~/ddis~
| Description  | Find all drug-drug interactions (DDI) in the DINTO ontology which involve only the /given/ drugs                                 |
| Methods      | ~POST~                                                                                                                           |
| Request Body | An object containing a list of /drug references/, named ~drugs~, where a /drug reference/ is either ~dinto:DB123~ or ~chebi:123~ |
| Returns      | A list containing pairs of the canonical URI for a drug-drug interaction, as well as its English Label                           |

**** Example
***** Request Body
 #+BEGIN_SRC json
 {
   "drugs": [
     "dinto:db0021",
     "dinto:db3040",
     "chebi:43259",
     "dinto:db2304909",
     "chebi:01342"
   ]
 }
 #+END_SRC
***** Response Body
 #+BEGIN_SRC json
 [
   {
     "label" : "tranylcypromine/vilazodone DDI",
     "uri" : "http://purl.obolibrary.org/obo/DINTO_08338"
   },
   {
     "label" : "penbutolol/methysergide DDI",
     "uri" : "http://purl.obolibrary.org/obo/DINTO_07540"
   },
   {
     "label" : "drospirenone/heparin DDI",
     "uri" : "http://purl.obolibrary.org/obo/DINTO_03086"
   }
 ]
 #+END_SRC
