* Asclepius ⚕
Flask endpoint for querying DINTO. Supports querying for all drugs listed, as well as finding all, or specific drug-drug interactions.

** Setup
*** DINTO Ontology Selection
By default, the application uses ~DINTO/DINTO 1/DINTO_1.owl~ as its ontology.
This can be overriden by setting the ~ASCLEPIUS_ONTOLOGY_FILE~ environment variable.

*Note*: As the ontology is rather large, startup can take upwards of 3 minutes.

** Endpoints
*** ~/ping~
| Description | Check endpoint availability |
| Methods     | ~GET~                       |
| Parameters  | None                        |
| Returns     | HTTP 204 (No Content)       |

*** ~/all_drugs~
| Description | Find all drugs in the DINTO ontology                                                  |
| Methods     | ~GET~                                                                                 |
| Parameters  | None                                                                                  |
| Returns     | A list containing pairs of the canonical URI for a drug, as well as its English Label |

**** Example
***** Response Body (Truncated)
#+BEGIN_SRC json
[
  {
    "label": "carbapenem MM22383",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_58998"
  },
  {
    "label": "adenosine-5'-ditungstate",
    "uri": "http://purl.obolibrary.org/obo/DINTO_DB02183"
  },
  {
    "label": "(5z)-13-chloro-14,16-dihydroxy-3,4,7,8,9,10-hexahydro-1h-2-benzoxacyclotetradecine-1,11(12h)-dione",
    "uri": "http://purl.obolibrary.org/obo/DINTO_DB08346"
  },
  {
    "label": "etoposide",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_4911"
  }
]
#+END_SRC

*** ~/all_ddis~
| Description | Find all drug-drug interactions (DDIs) in the DINTO ontology                                           |
| Methods     | ~GET~                                                                                                  |
| Parameters  | None                                                                                                   |
| Returns     | A list containing pairs of the canonical URI for a drug-drug interaction, as well as its English Label |

**** Example
***** Response Body (Truncated)
#+BEGIN_SRC json
[
  {
    "label": "torasemide/trandolapril DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_11031"
  },
  {
    "label": "cimetidine/heroin DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_02733"
  },
  {
    "label": "methylergonovine/telithromycin DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_10154"
  }
]
#+END_SRC

*** ~/ddis~
| Description  | Find all drug-drug interactions (DDI) in the DINTO ontology which involve only the /given/ drugs                                 |
| Methods      | ~POST~                                                                                                                           |
| Request Body | An object containing a list of /drug references/, named ~drugs~, where a /drug reference/ is either ~dinto:DB123~ or ~chebi:123~ |
| Returns      | A list containing pairs of the canonical URI for a drug-drug interaction, as well as its English Label                           |

**** Example
***** Request Body
 #+BEGIN_SRC json
{"drugs": ["chebi:421707", "chebi:465284", "dinto:DB00503", "chebi:9342"]}
 #+END_SRC
***** Response Body
 #+BEGIN_SRC json
[
  {
    "label": "abacavir/ganciclovir DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_05759"
  },
  {
    "label": "abacavir/ritonavir DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_11043"
  }
]
 #+END_SRC
